[tool.black]
line-length = 120
target-version = ['py310']
extend-exclude = ['test/']

[tool.mypy]
python_version = '3.10'
plugins = 'numpy.typing.mypy_plugin'
exclude = ['test/']

[[tool.mypy.overrides]]
module = 'cv2'
ignore_missing_imports = true