io:
  inputs:
    - type: FileReader
      path: ./data/input/lr/starboard_0120220423163949.mp4
      skip: 9.2
      speed_up: 4
    - type: FileReader
      path: ./data/input/lr/port_0120220423162959.mp4
      speed_up: 4
  outputs:
    - type: ScreenOutput
      title: Stitched
    # - type: FileWriter
    #   dimensions: [1280, 720]
    #   source: OUTPUT
    #   filename: "{date}_stitching.mp4"
stitching:
  # homography:
  #   type: NoWarpingHandler
  #   save_to_file: True
  #   continous_recomputation: False
  homography:
    type: FileLoadHandler
  # homography:
  #   type: OrbRansacHandler
  #   continous_recomputation: False
  #   save_to_file: True
  #   orb_features: 50000
  #   min_matches: 10
  #   relevant_area_one: [[200, 200], [900, 500]]
  #   relevant_area_two: [[200, 200], [900, 500]]
  # masking:
  #   type: NaiveFading
  #   continous_recomputation: False
  #   save_to_file: True
  masking:
    type: FileLoadHandler
  # masking:
  #   type: SeamFinding
  #   continous_recomputation: True
  #   save_to_file: True
  #   preferred_seam: [[475, 400], [725, 400]]
  # masking:
  #   type: SeamCarving
  #   continous_recomputation: True
  #   save_to_file: True
  #   blocked_area_one: [[540, 70], [1300, 360]]
  #   blocked_area_two: [[0, 420], [825, 700]]
  # masking:
  #   type: SeamCarvingWide
  #   continous_recomputation: True
  #   save_to_file: True
  #   blocked_area_one: [[540, 70], [1300, 360]]
  #   blocked_area_two: [[0, 420], [825, 700]]
  # masking:
  #   type: HorizontalSeamCarving
  #   continous_recomputation: True
  #   save_to_file: True
  #   half_window_size: 3
  #   gauss_size: 17
  #   yrange: [0.3, 0.7]
misc:
  automatic_restart: True
logging:
  version: 1
  formatters:
    precise:
      format: "%(asctime)s.%(msecs)03d: %(levelname)s@%(module)s:%(lineno)d(%(funcName)s) - %(message)s."
      datefmt: "%Y-%m-%d %H:%M:%S"
    brief:
      format: "%(asctime)s.%(msecs)03d: %(levelname)s - %(message)s."
      datefmt: "%H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: precise
      filename: log/suturis.log
      encoding: utf-8
      when: MIDNIGHT
      backupCount: 14
  root:
    level: DEBUG
    handlers: [console, file]
