io:
  inputs:
    - type: FileReader
      path: ./data/examples/files/2022-04-23/starboard_0120220423163949.mp4
      skip: 79.8
      speed_up: 3
      single_frame: False
    - type: FileReader
      path: ./data/examples/files/2022-04-23/port_0120220423162959.mp4
      skip: 73
      speed_up: 3
      single_frame: False
  outputs:
    # - type: ScreenOutput
    #   title: Stitched
    #   window_size: [1280, 720]
    - type: FileWriter
      dimensions: [1280, 720]
      source: OUTPUT
      filename: "{date}_stitching.mp4"
      fps: 30
stitching:
  preprocessing:
    # - type: DebugColoring
    # - type: TextRemoval
    #   needed_for_computation: False
    #   text_areas_one:
    #     - [[454, 17], [823, 41]] # Text Top
    #     - [[1052, 671], [1264, 698]] # Text Bot
    #   text_areas_two:
    #     - [[454, 17], [823, 41]] # Text Top
    #     - [[1085, 671], [1264, 698]] # Text Bot
  # homography:
  #   type: NoWarpingHandler
  #   save_to_file: False
  homography:
    type: FileLoadHandler
    path: ./data/examples/files/homography.npz
  # homography:
  #   type: BasicOrbHandler
  #   caching_enabled: False
  #   save_to_file: False
  #   orb_features: 10000
  #   min_matches: 10
  # homography:
  #   type: OptimizedSiftHandler
  #   caching_enabled: True
  #   save_to_file: False
  #   sift_features: 10000
  #   min_matches: 10
  #   relevant_areas_one:
  #     # - [[200, 200], [900, 500]]
  #     - [[191, 209], [270, 450]] # Stern
  #     - [[191, 209], [555, 282]] # Portside
  #     - [[188, 391], [558, 463]] # Starboard
  #     - [[844, 309], [907, 400]] # Bow
  #     - [[645, 325], [685, 365]] # Circle
  #   relevant_areas_two:
  #     # - [[200, 200], [900, 500]]
  #     - [[158, 243], [199, 462]] # Stern
  #     - [[158, 243], [527, 300]] # Portside
  #     - [[154, 406], [521, 473]] # Starboard
  #     - [[784, 345], [847, 434]] # Bow
  #     - [[601, 356], [634, 398]] # Circle
  # masking:
  #   type: NaiveFading
  # masking:
  #   type: FileLoadHandler
  #   invert: True
  # masking:
  #   type: SeamFinding
  #   caching_enabled: True
  #   save_to_file: False
  #   preferred_seam: [[475, 400], [725, 400]]
  # masking:
  #   type: SeamCarvingWide
  #   caching_enabled: True
  #   save_to_file: False
  #   blocked_area_one: [[540, 70], [1400, 360]]
  #   blocked_area_two: [[0, 420], [825, 700]]
  # masking:
  #   type: HorizontalSeamCarving
  #   caching_enabled: True
  #   save_to_file: False
  #   invert: False
  #   half_window_size: 5
  #   gauss_size: 27
  #   yrange: [0.4, 0.6]
  masking:
    type: StraightSeam
    caching_enabled: True
    save_to_file: True
    invert: False
    index: 400
    vertical: False
  postprocessing:
    - type: Cropper
      caching_enabled: True
      threshold: 0.02
    # - type: Rotation
    #   caching_enabled: True
    #   angle_deg: 90
misc:
  automatic_restart: False
  enable_debug_outputs: True
  enable_debug_keyinputs: True
logging:
  version: 1
  formatters:
    precise:
      format: "%(asctime)s.%(msecs)03d: %(levelname)s@%(module)s:%(lineno)d(%(funcName)s) - %(message)s."
      datefmt: "%Y-%m-%d %H:%M:%S"
    brief:
      format: "%(asctime)s.%(msecs)03d: %(levelname)s - %(message)s."
      datefmt: "%H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: precise
      filename: log/suturis.log
      encoding: utf-8
      when: MIDNIGHT
      backupCount: 14
  root:
    level: DEBUG
    handlers: [console, file]
