io:
  inputs:
    - type: FileReader
      path: ./data/input/lr/starboard_0120220423163949.mp4
      skip: 9.2
      speed_up: 2
    - type: FileReader
      path: ./data/input/lr/port_0120220423162959.mp4
      speed_up: 2
  outputs:
    - type: ScreenOutput
      title: Stitched
    # - type: FileWriter
    #   dimensions: [1280, 720]
    #   source: OUTPUT
    #   filename: "{date}_stitching.mp4"
stitching:
  homography:
    type: OrbRansacHandler
    continous_recomputation: False
    orb_features: 50000
    min_matches: 10
  # masking:
  #   type: SeamFinding
  #   continous_recomputation: True
  #   preferred_seam: [[475, 400], [725, 400]]
  # masking:
  #   type: SeamCarving
  #   continous_recomputation: True
  #   blocked_area_one: [[540, 70], [1300, 360]]
  #   blocked_area_two: [[0, 420], [825, 700]]
  masking:
    type: HorizontalSeamCarving
    continous_recomputation: True
    blocked_area_one: [[540, 70], [1300, 360]]
    blocked_area_two: [[0, 420], [825, 700]]
misc:
  automatic_restart: True
logging:
  version: 1
  formatters:
    precise:
      format: "%(asctime)s.%(msecs)03d: %(levelname)s@%(module)s:%(lineno)d(%(funcName)s) - %(message)s."
      datefmt: "%Y-%m-%d %H:%M:%S"
    brief:
      format: "%(asctime)s.%(msecs)03d: %(levelname)s - %(message)s."
      datefmt: "%H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: precise
      filename: log/suturis.log
      when: MIDNIGHT
      backupCount: 14
  root:
    level: DEBUG
    handlers: [console, file]
